### ISSUE TITLE
Bug with 2 open reply forms

### ISSUE THREAD

**Issue by telldanesaloca** [b04rd/flask_reddit#21]
Actions order:
1. Open 2 reply forms in different branches of comment
2. Post comment in 1st branch.
3. Comment in 1st branch posted, form in 2nd still open. Post reply to comment in 1st branch.
4. Result - this comment disappears.
![bug](https://cloud.githubusercontent.com/assets/17653194/14041141/3b08f522-f27f-11e5-9136-aeb9e2a248f4.png)

**Comment by telldanesaloca** [comment]
And after that I can add only one reply to "branch2 for demo". Next replies disappear too.

**Comment by telldanesaloca** [comment]
Illustration for the new problem after the fix (user changed his mind about where he'd like to reply):
![netuda](https://cloud.githubusercontent.com/assets/17653194/14059307/2dedadfe-f34e-11e5-996c-824498f65bd1.png)

**Comment by yl3dy** [comment]
Looks like fixed, probably during fixing of #23.
