### ISSUE TITLE
Disappearing comments via mobile connection

### ISSUE THREAD

**Issue by telldanesaloca** [b04rd/flask_reddit#23]
When user has not very good mobile connection, some comments disappear.
May be it's good idea to add exeption handling for timeouts, lost connection, network change etc.
Solution like: "This comment _quote_ hasn't been send. Try again?" would be perfect.

**Comment by yl3dy** [comment]
Possible solution: sane error checking after AJAX post + issue a message when sending hasn't succeeded, then try to send several times (message via JS on bootstrap alert). Likely affects also #21, as it leads to incorrect DOM object names.
