### ISSUE TITLE
button "send message" leads to 404 error page

### ISSUE THREAD

**Issue by telldanesaloca** [b04rd/flask_reddit#8]
![untitled-1](https://cloud.githubusercontent.com/assets/17653194/13538866/f1852884-e25d-11e5-9c55-92cced7e1e81.png)
There is a button at the user profile page (http://mipt.me/users/*username*) with the name "Send message" ("Отправить сообщение") and link "http://mipt.me/threads/frontpage/submit/".
Now it leads to the 404 error page.

**Comment by yl3dy** [comment]
Disabled this button until private messages are implemented.
